Fixed the error in the Overallstats.comprank by changing it to a Opti…
nabijaczleweli/OWAPI.rs pull request #2
Opened 2017-09-08 22:54 UTC by Caemor

…on<u32> instead of a u32. Also adapted the tests to it and changed it so that both null and some value are tested now

To solve the issue of the null value from the owapi.

2017-09-08 23:03 UTC, Caemor commented
Travis had a problem with a openssl command. Not sure how to fix this.

2017-09-09 08:56 UTC, nabijaczleweli requested changes

2017-09-09 08:56 UTC, nabijaczleweli commented on tests/v3/statistics.rs
> +
Amend/squash without these newlines and yer :+1:

2017-09-09 09:24 UTC, nabijaczleweli commented
Travis breaks of its own accord occasionally, worry not.

2017-10-29 01:52 UTC, nabijaczleweli approved these changes

2017-10-29 12:19 UTC, Caemor commented
Is sth still missing? It seems Travis just couldn't get the the aquire of the API in time.

2017-10-29 12:49 UTC, nabijaczleweli commented
No no, all is fine. I'm just really run up with work this week, I'll be merging later today :)

2017-10-29 19:47 UTC, merged

2017-10-29 19:53 UTC, nabijaczleweli commented
Released in [`v2.0.0`](https://github.com/nabijaczleweli/OWAPI.rs/releases/tag/v2.0.0)